print('Gegevensinvoer')
naam = input('type hier uw naam       : ')
adres = input("type hier uw adres      : ")
postcode = input('type hier uw postcode   : ')
woonplaats = input('type hier uw woonplaats : ')

print('-----------------------------------')
print()
print('Naam       : ' + naam)
print('adres      : ' + adres)
print('postcode   : ' + postcode)
print('woonplaats : ' + woonplaats)
print()
print('-----------------------------------')